// Fifty recent YouTube reactions and critiques published after the September 2026 verdict reports.
// Titles make the destinations auditable; the first entry starts at the user's suggested timestamp.
window.CITY_CRITICISM_VIDEOS = [
  {id:'05qPi-rSbho',title:'Manchester City Are Scum.',start:60},
  {id:'yH9yUhh1a8c',title:'The Man City Situation Just Got Worse..'},
  {id:'gbU8RyrbdfA',title:'Manchester City are F**KED. Here\'s Why.'},
  {id:'SDCHF4qwF1c',title:'Man City Are In Huge Trouble...'},
  {id:'kEwGPilgz4s',title:'The Satisfying Fall Of Manchester City'},
  {id:'angDQhqfiMo',title:'The Man City Situation Just Got A LOT Worse'},
  {id:'yLXvJuLD18c',title:'Are Manchester City F***ed?'},
  {id:'Qi1QmTf5Mtg',title:'MAN CITY ARE GUILTY!'},
  {id:'MlCd-Xx5U4o',title:'Man City fans before being found guilty VS now'},
  {id:'BNIkqSDtA18',title:'MAN CITY HAVE RUINED FOOTBALL'},
  {id:'9o_7FFuets0',title:'They Are DONE! City 115 CONFIRMED! Goldbridge Reacts!'},
  {id:'mv1cHsHlQgw',title:'Manchester City guilty of arranging sham contracts and inflating income by £830m'},
  {id:'2WlIPpYGgXc',title:'Man City Cheated A Premier League That Was Already RIGGED'},
  {id:'91orX3fZxlk',title:'The Manchester City Situation Got EVEN WORSE..'},
  {id:'3jPVy8HIpmg',title:'Why Man City Are Being Destroyed.'},
  {id:'Ef2teIGBDBg',title:'Manchester City Are Done.'},
  {id:'Fca53ux9SjM',title:'Man City Fans before & After GUILTY verdict.'},
  {id:'VQd-Luj-O1w',title:'MANCHESTER CITY FOUND GUILTY!'},
  {id:'IqvoluCO2QI',title:'Man City\'s £550M Nightmare Nobody Is Talking About'},
  {id:'boJvlLSpDL8',title:'Man City MUST be Punished!'},
  {id:'1l-H9uZdm-A',title:'The Likelihood Of Every Punishment Man City Could Actually Face'},
  {id:'5kidd6Yu5Ns',title:'Man City Are Guilty. The 114 Charges Verdict EXPLAINED!'},
  {id:'dO9sA9ul0NM',title:'I Read Man City\'s Full Guilty Verdict and It\'s WORSE Than You Think'},
  {id:'bbonNLzFfTA',title:'MANCHESTER CITY FOUND GUILTY OF 114 PREMIER LEAGUE FINANCIAL BREACHES'},
  {id:'whXKIhRERiE',title:'Reacting To Man City\'s 115 Charges Verdict'},
  {id:'Q5_hPiw-Giw',title:'THE END OF MAN CITY!'},
  {id:'OW255s2a9-U',title:'MAN CITY FOUND GUILTY!'},
  {id:'1JRO3MoCPKY',title:'BREAKING! MAN CITY FOUND GUILTY OF ALL CHARGES!'},
  {id:'ztchhz20Y28',title:'Should Man City Be Relegated?'},
  {id:'g0ODYNrCT2w',title:'The Premier League Exposed The TRUTH About Man City..'},
  {id:'GafGP7vCc3c',title:'The Man City scandal is the biggest in sporting history'},
  {id:'BqApGo4ZM-o',title:'IT\'S OFFICIAL: MANCHESTER CITY GUILTY OF ALL CHARGES!'},
  {id:'Tp0vdioQmRw',title:'More TROUBLE for Man City! Sham Contracts & $1.1B Breach'},
  {id:'5AVMBdzSO6c',title:'Kieran Maguire reacts to Manchester City\'s guilty verdict'},
  {id:'ifvAHuTo29A',title:'The Blueprint for Man City\'s Punishment'},
  {id:'DdGgrZSEiug',title:'The Punishment Man City Are Facing Is HUGE If They Fail To Win Appeal!'},
  {id:'CNDodAnoSYc',title:'We\'re Witnessing The End of Manchester City'},
  {id:'QNzszllxg90',title:'We Need To Talk About Manchester City Being Found Guilty...'},
  {id:'_eItvq_ZjqI',title:'This is what happens if Man City Really do Get Punished'},
  {id:'lG8u8WBrlv8',title:'MAN CITY FANS FINALLY REALISING ITS OVER FOR THEM'},
  {id:'NkXik882heM',title:'MAN CITY FOUND GUILTY OF ALL CHARGES! EXPRESSIONS REACTS'},
  {id:'wBdLHbjL154',title:'MANCHESTER CITY ARE THE BIGGEST CHEATS IN FOOTBALL HISTORY!'},
  {id:'Hd1x0pSJcZg',title:'Man City Guilty Of ALL Charges!'},
  {id:'lJxW4Wr6tRs',title:'MAN CITY GUILTY & KICKED OUT OF FOOTBALL?!'},
  {id:'OnamT89KGNk',title:'BIGGEST SPORTING CHEATING SCANDAL EVER '},
  {id:'wUEwLuK7tWU',title:'Regista Football Podcast: City found GUILTY'},
  {id:'UFL-jwWQXWY',title:'Relegation IS NOT Enough for Man City'},
  {id:'y7VPogOtYM0',title:'City HAVE To Be Relegated! Piers & Simon'},
  {id:'4crNa7BP9a0',title:'Guilty (Football Iconic)'},
  {id:'B9EarfqddBM',title:'Sports lawyer explains what Manchester City charges verdict means'},
];
